### ISSUE TITLE
After the ssl was added, the app started to hang in production enviroment

### ISSUE THREAD

**Issue by OlehOnufrak** [ruby-jp/websocket-client-simple#14]
If the connection URL contains 'wss', then connection works and we can receive messages but nothing works except websocket connection (controller actions etc.)

**Comment by unasuke** [comment]
Thank you for your report. Could someone show me reproductive script? Is v0.5.1 works intentionally?

**Comment by OlehOnufrak** [comment]
class ApplicationController < ActionController::Base
  include UserMessages::MessagesCountWebSocket 
  before_action :authenticate, :close_connections, :get_messages_count
end

module UserMessages::MessagesCountWebSocket
  require 'websocket-client-simple'

  def get_messages_count
    ws = WebSocket::Client::Simple.connect('wss://some_adress:4324')

    ws.on :open do
      ws.send({ action: "connect", login: "Test_chat", token: ENV['CHAT_TOKEN'], business_key: "Test#{business_id}" }.to_json)
      ws.send({ action: "get_messages_count" }.to_json)
    end

    ws.on :message do |msg|
    if msg.data.present?
      message = JSON.parse msg.data
      case
      when message['users']
        Rails.cache.redis.set("Test_#{business_id}", Marshal.dump(message['users'].first))
        when message["r_action"] == "new_message" && !message["sender_id"]
          unless Rails.cache.redis.get('exist_message?') == message
            Rails.cache.redis.set('exist_message?', message)
            ActionCable.server.broadcast('get_messages_count_channel', update_for_count: business_id, 
                                         chat_id:message['chat_id'], msg_data:  message['msg_data'], 
                                         msg_time: message['timestamp'])
            if current_chat_id == message['chat_id']
              ws.send({ action: "update_last_seen", chat_id: message['chat_id'], msg_id: message['msg_id'] }.to_json)
            end
          end
        when message['chats']
          Rails.cache.redis.set("Test_section#{business_id}", Marshal.dump(message['chats'].first))
        end
      end
    end

**Comment by OlehOnufrak** [comment]
Hangs after - ws.send({ action: "connect", login: "Test_chat", token: ENV['CHAT_TOKEN'], business_key: "Test#{business_id}" }.to_json)

**Comment by unasuke** [comment]
@OlehOnufrak  Thank you for script! But is bit complex because it looks a part of rails.

![image](https://user-images.githubusercontent.com/4487291/199517314-e6d4ab35-d7fd-40d1-986b-6523facaf277.png)

I tried example ruby scripts(in this repo) through ngrok for wss, it works.

I need more information.

**Comment by unasuke** [comment]
Could you provide entire app, someone?

**Comment by OlehOnufrak** [comment]
> Could you provide entire app, someone?

OK, but I need some time...

**Comment by OlehOnufrak** [comment]
Sorry for such a late reply. The reason was the configuration of the server under the docker machine. The gem works properly locally and in production. And thank you for your time!
