### ISSUE TITLE
Can we have the current state of the code base without required_ruby_version = '>=2.6.9'

### ISSUE THREAD

**Issue by prateek-ap** [ruby-jp/websocket-client-simple#18]
Hi, @unasuke 
I need current state of the client to be run on ruby version '>=2.4.0'
Can you please release a version without **spec.required_ruby_version** or atleast for '>=2.4.0'.
If you want to remove support for EOL ruby version, we can re-release with '>=2.7' as 2.6 is also EOL.

**Comment by unasuke** [comment]
@prateek-ap Sorry. We didn't plan a new release of change supported ruby version to `>=2.4.0`.

If you want to run this gem on Ruby 2.4 family, you can fork this repository and change `required_ruby_version` in gemspec, then specify your fork into your Gemfile.

I think this document might help you.
https://bundler.io/v2.4/man/gemfile.5.html#SOURCE

**Comment by prateek-ap** [comment]
@unasuke i need to use this gem in another gem gemspec and In gemspec we can't specify github path for the dependency.
What i see from the commit(https://github.com/ruby-jp/websocket-client-simple/commit/43541f5fbc3259271c3f262d9bc99e8d91e0dd47) is that, `required_ruby_version` was added explicitly just because of EOL, other wise there is no any obstacle in using the gem with older version.
required_ruby_version = '>= 2.6.9' is too restrictive when we can support older versions as well. Right now we can widen the scope of use of this client just by releasing a newer version without required_ruby_version and then again re-release to limit the scope(if we want). In my opinion we should not be that much restrictive explicitly for ruby version when we are already have compatibility with older version. Please consider this request so that i can open a PR, else i will need to rewrite the whole client again and publish on the rubygems.

**Comment by unasuke** [comment]
@prateek-ap For reference, could you tell me what "another gem"  you say you have this gem as a dependency?

**Comment by prateek-ap** [comment]
@unasuke Gem is under development, neither the gem is published nor the repository is public yet.

**Comment by unasuke** [comment]
Hmm...

@prateek-ap  Indeed, I made requied_ruby_version to ">= 2.6.9" for the migration pass.
But I think it's not a good idea to support writing ruby code for 2.4 in 2023. So I don't think it's not "too restrictive".

Why do you want to support ruby 2.4 in now?

**Comment by prateek-ap** [comment]
@unasuke We are developing a new gem for our customers which uses [websocket-client-simple](https://github.com/ruby-jp/websocket-client-simple) but customers are still on ruby version 2.4 and we need to give support for 2.4 as well. Hence, it is required that latest websocket client code base also support ruby 2.4

**Comment by unasuke** [comment]
@prateek-ap Ok. I got your situation. ..And you couldn't use this gem v0.3.1 (with no version requirement) for some reason, right?

**Comment by prateek-ap** [comment]
@unasuke very well understood! `cert_store = options[:cert_store]` passing was added later on which is a mandatory feature for me.

**Comment by unasuke** [comment]
@prateek-ap How is the submodule way? Including this gem's codes by submodule in your gem, then ruby version restriction is under your control.

**Comment by prateek-ap** [comment]
@unasuke That is the last option for me, to keep this gems code along with my gem... but there comes maintainability concerns... That's why i was thinking, if you can push a version for me without require_ruby_version. That will also solve problem for others like me using this gem.

**Comment by prateek-ap** [comment]
@unasuke Also it would be great if you can add connect timeout option as well.

**Comment by unasuke** [comment]
@prateek-ap You told, "there comes maintainability concerns". That is correct in some positions.

But I think using EOL-ed ruby is more, more, more...comes maintainability and security concern. In addition, this gem is about websocket. It's a communicate with another host over the internet. In this situation, using EOL-ed ruby is too dangerous.

Your position is that you cannot force your customers to use the currently supported version of Ruby. I understand this as well.

So I think it is better to tell your customers there is a difficulty in maintainability and convince them to use the currently supported Ruby.

**Comment by prateek-ap** [comment]
Ruby authors are quite aggressive towards Ruby version life... every 3 years they EOL the released ruby version.
@unasuke [Websocket-client-simple](https://github.com/ruby-jp/websocket-client-simple) gem uses [websocket](https://github.com/imanel/websocket-ruby) which also uses `require_ruby_version >= 
2` . The only reason most of the gem authors give a flexible required_ruby_version is to widen the usage of the gem and backward compatibility with the legacy codes. Here is the ref: https://github.com/imanel/websocket-ruby/blob/master/websocket.gemspec#L22
My request is to release just one version without required_ruby_version and then you can again release a new version with supporting only non-EOL Ruby. I hope this clarifies. Thank you

**Comment by unasuke** [comment]
> Ruby authors are quite aggressive towards Ruby version life

I don't think so. 

> flexible required_ruby_version is to widen the usage of the gem and backward compatibility with the legacy codes.

The websocket gem's strategy maybe so, but this gem is not.

If you cannot bundle this gem's code as a submodule (and modify it), please use websocket gem directly.

**Comment by prateek-ap** [comment]
@unasuke Okay... Maybe i will go that route. Thanks!
