### ISSUE TITLE
Error: unexpected token at 'Pong timeout'

### ISSUE THREAD

**Issue by moviendome** [ruby-jp/websocket-client-simple#28]
Hi, I'm using this gem to connect to Binance websocket and everything goes well until ~10 mins when I receive this message: `Error: unexpected token at 'Pong timeout'`.

I couldn't find documentation related in the gem but I can read at Binance docs that Websocket server will send a ping frame every 3 minutes:
- If the websocket server does not receive a pong frame back from the connection within a 10 minute period, the connection will be disconnected.
- When you receive a ping, you must send a pong with a copy of ping's payload as soon as possible.
- Unsolicited pong frames are allowed, but will not prevent disconnection. It is recommended that the payload for these pong frames are empty.

Anyone knows how I could solve this?
Thanks in advance!

**Comment by unasuke** [comment]
@moviendome solved?
